# Generated by Django 6.0 on 2026-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency_type', models.CharField(choices=[('KUKL', 'KUKL'), ('NEA', 'NEA'), ('MUNICIPALITY', 'Municipality')], max_length=30)),
            ],
        ),
    ]
