# Generated by Django 6.0 on 2026-01-02 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='agencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
